### ISSUE TITLE
Erro occured when using a template file

### ISSUE THREAD

**Issue by gabriel19913** [NilsJPWerner/autoDocstring#149]
**Describe the bug**
When using a template file a error occured

**Versions (please complete the following information):**
- autoDocstring Version: 0.5.3
- Operating System: Pop OS 20.04
- Vscode Version: 1.46.1

**Original Code (with line to generate on):**
```python
# generate on this line
```

**Expected Result:**
```python
    [summary]

    Returns
    -------
    [type]
        [description]
```

**Actual Result:**
```python
A error occured
```

**Stack trace:**
If an error was reported by autodocstring please copy the stack trace from the `autoDocstring` output channel.
```
[INFO 22:12:27.218] Generating Docstring at line: 13
[ERROR 22:12:27.221] Error: EISDIR: illegal operation on a directory, read
	at Object.getCustomTemplate <autoDocstring>/out/docstring/get_template.js:19:17
	at AutoDocstring.getTemplate <autoDocstring>/out/generate_docstring.js:50:31
	at AutoDocstring.generateDocstringSnippet <autoDocstring>/out/generate_docstring.js:33:80
	at AutoDocstring.generateDocstring <autoDocstring>/out/generate_docstring.js:21:39
	at  <autoDocstring>/out/extension.js:15:34
```

**Additional context**

**Comment by NilsJPWerner** [comment]
This error is saying that the path is a Directory not a file. What is the path of your custom template?
