### ISSUE TITLE
TypeError when activated

### ISSUE THREAD

**Issue by liam-clink** [NilsJPWerner/autoDocstring#295]
**Describe the bug**
When trying to generate text in any function, the extension fails.

**Versions (please complete the following information):**

-   autoDocstring Version: 0.6.1
-   Operating System: Windows 10
-   Vscode Version:1.96.0

**Original Code (with line to generate on):**

```python
def foo(bar):
    # generate on this line
    return 0
```

**Debug log:**
Set `autoDocstring.logLevel` to "Debug", recreate the bug, and then copy the debug logs from the `autoDocstring` output channel.

```
[ERROR 19:51:05.873] TypeError: Cannot read properties of undefined (reading 'toString')
	at AutoDocstring.getTemplate <autoDocstring>/out/generate_docstring.js:48:66
	at AutoDocstring.generateDocstringSnippet <autoDocstring>/out/generate_docstring.js:35:80
	at AutoDocstring.generateDocstring <autoDocstring>/out/generate_docstring.js:23:39
```

**Comment by Dastfjyv3457** [comment]
[ERROR 19:51:05.873] TypeError: Cannot read properties of undefined (reading 'toString')
	at AutoDocstring.getTemplate <autoDocstring>/out/generate_docstring.js:48:66
	at AutoDocstring.generateDocstringSnippet <autoDocstring>/out/generate_docstring.js:35:80
	at AutoDocstring.generateDocstring <autoDocstring>/out/generate_docstring.js:23:39

**Comment by Dastfjyv3457** [comment]
> **Describe the bug** When trying to generate text in any function, the extension fails.
> 
> **Versions (please complete the following information):**
> 
> * autoDocstring Version: 0.6.1
> * Operating System: Windows 10
> * Vscode Version:1.96.0
> 
> **Original Code (with line to generate on):**
> 
> ```python
> def foo(bar):
>     # generate on this line
>     return 0
> ```
> 
> **Debug log:** Set `autoDocstring.logLevel` to "Debug", recreate the bug, and then copy the debug logs from the `autoDocstring` output channel.
> 
> ```
> [ERROR 19:51:05.873] TypeError: Cannot read properties of undefined (reading 'toString')
> 	at AutoDocstring.getTemplate <autoDocstring>/out/generate_docstring.js:48:66
> 	at AutoDocstring.generateDocstringSnippet <autoDocstring>/out/generate_docstring.js:35:80
> 	at AutoDocstring.generateDocstring <autoDocstring>/out/generate_docstring.js:23:39
> ```



> **Describe the bug** When trying to generate text in any function, the extension fails.
> 
> **Versions (please complete the following information):**
> 
> * autoDocstring Version: 0.6.1
> * Operating System: Windows 10
> * Vscode Version:1.96.0
> 
> **Original Code (with line to generate on):**
> 
> ```python
> def foo(bar):
>     # generate on this line
>     return 0
> ```
> 
> **Debug log:** Set `autoDocstring.logLevel` to "Debug", recreate the bug, and then copy the debug logs from the `autoDocstring` output channel.
> 
> ```
> [ERROR 19:51:05.873] TypeError: Cannot read properties of undefined (reading 'toString')
> 	at AutoDocstring.getTemplate <autoDocstring>/out/generate_docstring.js:48:66
> 	at AutoDocstring.generateDocstringSnippet <autoDocstring>/out/generate_docstring.js:35:80
> 	at AutoDocstring.generateDocstring <autoDocstring>/out/generate_docstring.js:23:39
> ```

**Comment by Dastfjyv3457** [comment]
> **Describe the bug** When trying to generate text in any function, the extension fails.
> 
> **Versions (please complete the following information):**
> 
> * autoDocstring Version: 0.6.1
> * Operating System: Windows 10
> * Vscode Version:1.96.0
> 
> **Original Code (with line to generate on):**
> 
> ```python
> def foo(bar):
>     # generate on this line
>     return 0
> ```
> 
> **Debug log:** Set `autoDocstring.logLevel` to "Debug", recreate the bug, and then copy the debug logs from the `autoDocstring` output channel.
> 
> ```
> [ERROR 19:51:05.873] TypeError: Cannot read properties of undefined (reading 'toString')
> 	at AutoDocstring.getTemplate <autoDocstring>/out/generate_docstring.js:48:66
> 	at AutoDocstring.generateDocstringSnippet <autoDocstring>/out/generate_docstring.js:35:80
> 	at AutoDocstring.generateDocstring <autoDocstring>/out/generate_docstring.js:23:39
> ```
